 source = ~/.config/hypr/keybindings.conf
 source = ~/.config/hypr/windowrules.conf
 source = ~/.config/hypr/envs.conf
 source = ~/.config/hypr/decoration.conf
 source = ~/.config/hypr/input.conf

monitor=,2560x1440@165,auto,1

exec-once = waybar




